POST http://localhost:8080/conta
Content-Type: application/json

{
    "numero": 123,
    "agencia": "0789",
    "nomeTitular": "Joao Carlos Lima",
    "cpf": "81770673890",
    "dataDeAbertura": "2024-03-25",
    "saldo": 10,
    "tipo": "CORRENTE"

}

###

POST http://localhost:8080/conta
Content-Type: application/json

{
    "numero": 456,
    "agencia": "0789",
    "nomeTitular": "Maria Santos",
    "cpf": "14816082824",
    "dataDeAbertura": "2024-03-25",
    "saldo": 0,
    "tipo": "CORRENTE"

}

### 

GET http://localhost:8080/conta

### 

GET http://localhost:8080/conta/123

### 

GET http://localhost:8080/conta?cpf=81770673890

###

DELETE http://localhost:8080/conta/123

### 

POST http://localhost:8080/conta/123/deposito
Content-Type: application/json

{
    "valor": 100
}

### 

POST http://localhost:8080/conta/123/pix
Content-Type: application/json

{
    "valor": 100,
    "contaDestino": 456
}

